### ISSUE TITLE
When trying to do gg=ggplot(sheet0515,aes(StringField,BigIntField))+geom_bar() I get error in evaluating the argument 'x' in selecting a method for function 'column': Error in invokeJava(isStatic = FALSE, objId$id, methodName, ...)

### ISSUE THREAD

**Issue by fernandrez** [SKKU-SKT/ggplot2.SparkR#2]
gg=ggplot(sheet0515,aes(SEGMENT,Count))+geom_bar()
ggsave("/var/CMOR/data/Andres/sheet0515_port_count.png")
Saving 7 x 7 in image
16/04/05 13:54:55 ERROR RBackendHandler: col on 1109 failed
Error in column(callJMethod(x@sdf, "col", c)) :
  error in evaluating the argument 'x' in selecting a method for function 'column': Error in invokeJava(isStatic = FALSE, objId$id, methodName, ...) :
  org.apache.spark.sql.AnalysisException: Cannot resolve column name "y" among (x, PANEL, group, count, width);
        at org.apache.spark.sql.DataFrame$$anonfun$resolve$1.apply(DataFrame.scala:152)
        at org.apache.spark.sql.DataFrame$$anonfun$resolve$1.apply(DataFrame.scala:152)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.sql.DataFrame.resolve(DataFrame.scala:151)
        at org.apache.spark.sql.DataFrame.col(DataFrame.scala:708)
        at sun.reflect.GeneratedMethodAccessor171.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.spark.api.r.RBackendHandler.handleMethodCall(RBackendHandler.scala:141)
        at org.apache.spark.api.r.RBackendHandler.channelRead0(RBackendHandler.scala:86)
        at org.apache.spar

**Comment by fernandrez** [comment]
The ggplot2 example:
df <- data.frame(trt = c("a", "b", "c"), outcome = c(2.3, 1.9, 3.2))
ggplot(df, aes(trt, outcome)) +
  geom_bar(stat = "identity")

fails when the ggplot2.SparkR library is loaded as well

Error in get(name) : object 'StatIdentity_SparkR' not found

**Comment by fernandrez** [comment]
This Works: d <- ggplot(mtcars, aes(cyl, mpg)) + geom_point()

This Does not Work: d <- ggplot(sheet, aes(SEGMENT,AvgBal )) + geom_point()
Error in f(l = layers[[i]], d = data[[i]]) :
  attempt to apply non-function
SEGMENT: String
AvgBal: Double

**Comment by JonghyunBae** [comment]
First, geom_bar graph generally must not be used with a y aesthetic. So please input your aesthetics just one (SEGMENT or Count. Maybe SEGMENT is the best choice in your example).

Second, we did not implement stat option in geom_\* graph type yet. It will be updated ASAP!

Lastly, We did not implement geom_point graph type because point type is not good to show big data. So we did not implement geom_point and some other types. It will be applied in next major update (using sampling or other regression method).

If you want to see what graph types are supported, please visit our tutorial homepage (http://skku-skt.github.io/ggplot2.SparkR/)

Thanks for your report~!

**Comment by fernandrez** [comment]
thank you
